version: '3.3'

services:
  hamachi:
    container_name: hamachi
    hostname: hamachi
    volumes:
      - /volume1/docker/hamachi/config:/var/lib/logmein-hamachi
    network_mode: "host"
    restart: 'unless-stopped'
    privileged: true
    log-driver: "syslog"
    image: 'baandab/docker-hamachi-vpn:latest'
